### ISSUE TITLE
Allow has_closure_trees on polymorphic models

### ISSUE THREAD

**Issue by habibalamin** [mceachen/closure_tree#149]
Not sure what the right term for this is, but let me explain my situation.

I have a Comment model. I understand I can change the `parent_column_name` for closure_tree, so that it points to `commentable_id`. I haven't tried this yet, but I'm assuming that will cause problems, because a Comment can duplicate `commentable_id`s because of different `commentable_type`s. I'd like to limit closure_tree's methods to comments with `commentable_type` of `"Comment"` (except for root level comments, of course).

I had a brief search around and it seems like scopes on Rails 4 associations would help massively with this (though I expect that's also not going to be enough and I'm still on Rails 3 :disappointed:). Maybe I'm overthinking it. Maybe I just need to amend the `parent` method to return `nil` if the `commentable_type` is not the same as the model and a few other basic modifications.

**Comment by mceachen** [comment]
Sorry, polymorphic parent tables aren't supported.

**Comment by habibalamin** [comment]
Yes, I know. That's why I created the issue. :smiley:

I don't mind maintaining my own fork for that. Do you think it would be difficult to implement?

**Comment by mceachen** [comment]
Extremely difficult and, because the foreign keys can't have constraints
both in the model table and the closure table, I'd expect it to be
non-performant. You might as well not be using an rdbms if you're shipping
the r.

Not knowing your problem space, of course, but if you can rethink your
schema modeling to use sti polymorphism and just add  composition, you'll
be in a better place (just in general because of indexes, not just because
you can use this gem).
