### ISSUE TITLE
Use with paranoia gem ? 

### ISSUE THREAD

**Issue by tomaadland** [mceachen/closure_tree#224]
Can this be used with the [paranoia gem](https://github.com/rubysherpas/paranoia) ?

**Comment by mceachen** [comment]
I'd be really surprised if it did. Gems that modify default_scope normally
don't play well with others. The bulk updates that closure tree does all
over the place, for example, won't know to do updates rather than deletes.

It wouldn't be hard to spin up a rails console with both configured and
just try it out though. On a backup. With a fire extinguisher nearby.

**Comment by tomaadland** [comment]
That was my thoughts as well. Thank you for quick reply.
