### ISSUE TITLE
Update complete Tree

### ISSUE THREAD

**Issue by emmanuelmillionaer** [mceachen/closure_tree#251]
**Hi**, I would like to know the best way how to update a complete tree.

After a user modified a tree on the client-side, the server receives such an output:

     [{"id":"8","children":[{"id":"9"},{"id":"5"}]},{"id":"10","children":[{"id":"7"}]}]

That's the following tree:
   
     8 -> 9, 5
     10 -> 7

I would like to update the existing tree, following this structure, with the leaves in a sorted order. 

I tried following code:

```ruby
      def save_children(parent:,children:)
        children_sort = 0

        children.each do |child_attributes|
          child_page = Page.find(child_attributes["id"])
          child_page.update(parent_id: parent&.id, sort_order: children_sort)

          children_sort += 1

          if child_attributes["children"]
            save_children(parent: child_page, children: child_attributes["children"])
          end
        end
      end
      
      save_children(parent: nil, children:  [{"id":"8","children":[{"id":"9"},{"id":"5"}]},{"id":"10","children":[{"id":"7"}]}])
```

The code sometimes works, but sometimes it produces different trees then expected. 
**That's why I would like to know how you usually update the complete structure of a tree?**

Thanks

**Comment by mceachen** [comment]
That code should work, but it will end up in creating a number of extraneous calls to `.rebuild()` to maintain the hierarchies table. 

You aren't removing existing children before you add nodes to the parent, so those children_sort values will be random. If the problem is the `sort_order` being incorrect, and you are using deterministic ordering (see the README), I suspect that might be another issue.

The normally-terrible-idea of using [update_attribute](http://apidock.com/rails/v4.2.7/ActiveRecord/Persistence/update_attribute), or `save(false)`, followed by a call to `rebuild!` (possibly at the root level), would mean you only have to call `rebuild` once.

Note that all validations are skipped by `update_attribute`, so you're putting a lot of faith in the client to give you reasonable values. I'd pause and think about the damage a bad actor could do to your system.

I'd also be afraid of concurrent calls to `save_children`, which will certainly scramble your tree. You should do that work with an advisory lock, most likely.

**Comment by emmanuelmillionaer** [comment]
@mceachen Thanks for your very elaborated answer. :slightly_smiling_face:  It helped a lot! 👍
