### ISSUE TITLE
Support for storing data in edges

### ISSUE THREAD

**Issue by alagu** [mceachen/closure_tree#259]
Hey @mceachen, thanks a ton for this gem!

Is it possible to store data in the edge?

**Comment by mceachen** [comment]
Edges are managed (created and destroyed) by closure tree with the
assumption that the isn't valuable extraneous data. If you **only* add**
nodes, and don't reparent them*, and your metadata columns are nullable,
then it should work, given the caveat that the additional edge model you
create doesn't confuse AR and CT.

Keep us posted on how it works out!

**Comment by alagu** [comment]
Thanks @mceachen, I realized that for my need I wanted multiple parents for a child hence I wanted to store data in edge. I'm ending up with duplicate nodes if I am building a tree structure.

Can you please help me what is AR and CT? Also can you suggest what are some good gems for building a DAG in rails?

Thanks for the prompt response!

**Comment by mceachen** [comment]
AR = Active Record
CT = Closure Tree

Note that multiple parents are doable with the closure trer data structure,
but I kept this gem's API much simpler by making the decision to only
support one parent.

So rather than storing metadata in edges, you might want to just fork this
gem's model class and just get an "addParent" method writing to the
heirarchy table. Children and descendant queries should work as they are.
