### ISSUE TITLE
Balanced tree

### ISSUE THREAD

**Issue by dexion** [mceachen/closure_tree#260]
Do this library have any tools for building balanced tree? Auto re-parenting nodeleaves? For buildings binary, ternary, ... *ry tree.

**Comment by mceachen** [comment]
Balanced trees, as far as I understand, can be rebalanced because node
ordering is the only constraint for that data model.

Closure tree has both ordering for siblings as well as hierarchy support,
so rebalancing would be nonsensical. You'd be giving children different
parents than what you originally assigned.

**Comment by dexion** [comment]
Yes, right. For example, I want build balanced binary tree(not search tree, so 
I do not care about the arrangement of the leaves). Node_1 already have 2 children (node_2 and node_3). Each nodes (node_2 and node_3) also have 2 children (node_4..node_7). If I add new node_8 with parent node_1 realy it should be node_4. When I want add node_9 for parent node_1 real parent should be node_4. And so on.. node10->node5. 

How I can find node (not leaf) with minimal level (so close for getted parent-node) and minimal number of children?

**Comment by mceachen** [comment]
Please read about the closure tree data structure. Ancestral and descendant
lineages aren't what you are looking for.

In your case, just use a database that has a performant index type for your
sortable column. I suggest postgres.

Good luck.
